#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#define BOARD_DISPLAY_HOR_RES 480
#define BOARD_DISPLAY_VER_RES 800
#define BOARD_DISPLAY_PANEL_HOR_RES 800
#define BOARD_DISPLAY_PANEL_VER_RES 480

#define BOARD_LCD_PCLK_HZ 15000000
#define BOARD_LCD_HSYNC_PULSE_WIDTH 1
#define BOARD_LCD_HSYNC_BACK_PORCH 42
#define BOARD_LCD_HSYNC_FRONT_PORCH 20
#define BOARD_LCD_VSYNC_PULSE_WIDTH 10
#define BOARD_LCD_VSYNC_BACK_PORCH 12
#define BOARD_LCD_VSYNC_FRONT_PORCH 4
#define BOARD_LCD_PCLK_ACTIVE_NEG 1
#define BOARD_LCD_BOUNCE_BUFFER_SIZE_PX (BOARD_DISPLAY_PANEL_HOR_RES * 10)

#define BOARD_LCD_HSYNC_PIN 39
#define BOARD_LCD_VSYNC_PIN 41
#define BOARD_LCD_DE_PIN 40
#define BOARD_LCD_PCLK_PIN 42
#define BOARD_LCD_DISP_PIN (-1)
#define BOARD_LCD_DATA_PINS {8, 3, 46, 9, 1, 5, 6, 7, 15, 16, 4, 45, 48, 47, 21, 14}

#define BOARD_TOUCH_I2C_SDA_PIN 19
#define BOARD_TOUCH_I2C_SCL_PIN 20
#define BOARD_TOUCH_I2C_ADDR 0x14
#define BOARD_TOUCH_I2C_FREQ 400000
#define BOARD_TOUCH_INT_PIN (-1)
#define BOARD_TOUCH_RST_PIN 38
#define BOARD_TOUCH_RST_ACTIVE_LEVEL 0
#define BOARD_TOUCH_STATUS_REG 0x814E

#define BOARD_BACKLIGHT_PIN 2
#define BOARD_BACKLIGHT_ACTIVE_LEVEL 1

#define BOARD_HX711_DATA_PIN 6
#define BOARD_HX711_SCK_PIN 16
#define BOARD_HX711_CALIBRATION_FACTOR 1.0f

#define BOARD_SERVO_PIN 15
#define BOARD_SERVO_CLOSED_ANGLE 0
#define BOARD_SERVO_OPEN_ANGLE 90

#define BOARD_BUTTON_1_PIN 35
#define BOARD_BUTTON_2_PIN 36

#define BOARD_LED_PIN 17

#endif